### ISSUE TITLE
Вычитка 15.07.2023

### ISSUE THREAD

**Issue by nickkolok** [SugarHedgehog/metodichki#3]
Стр. 1:

Место прохождение практики -> Место прохождени**я** практики

Стр. 2:

по теме стереометрия -> по теме "Стереометрия"
Прототип No27163 Открытый банк -> Прототип No27163 Открытого банка
(потому что далее в родительном падеже "подборки")

Стр. 3:
Проведено review шаблонов -> Проведено code review шаблонов

Стр. 5:
![image](https://github.com/SugarHedgehog/metodichki/assets/5008131/70b42a35-5b7f-4ab4-ab03-85079f4f619f)
Девятка перечёркнута пунктиром. В отчёт нужно отбирать лучшие примеры! Сделано очень много, этим можно и нужно гордиться!

To be continued

**Comment by nickkolok** [comment]
![image](https://github.com/SugarHedgehog/metodichki/assets/5008131/ebb38352-da67-4867-a085-a1e498260eb1)
Виден фантомный отрезанный кубик. И тут:
![image](https://github.com/SugarHedgehog/metodichki/assets/5008131/cd7e72c0-706e-4860-a574-1734a5e02d3c)
Возможно, это даже и не очень страшно.

Стр.11:
Во сколько раз увеличится объём пра-
вильного тетраэдра, если все его **полная
площадь поверхности увеличить** в 24 ра-
за?

А вообще отчёт хороший, мне нравится.

**Comment by SugarHedgehog** [comment]
>Виден фантомный отрезанный кубик. 
Как-нибудь смирится

**Comment by SugarHedgehog** [comment]
Всё исправлено
